name: Run plugin tests
on:
  push:
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        JAVA_VERSION: ["11", "17", "21"]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "${{ matrix.JAVA_VERSION }}"
      - name: Setup Nextflow
        uses: nf-core/setup-nextflow@v2

      - name: Install nf-test
        uses: nf-core/setup-nf-test@v1

      - name: Build plugin
        run: mvn install

      - name: Test the plugin
        env:
          NFT_DIFF: "pdiff"
          NFT_DIFF_ARGS: "--line-numbers --width 120 --expand-tabs=2"
        run: |
          ./tests.sh

      - name: Clean up
        if: always()
        run: |
          sudo rm -rf /home/ubuntu/tests/
